
# Ownership

```{r}
#| label: prep
#| output: false

# source general functions
source(paste0(here::here(), "/1_code/0000_general/general_utils.R"))

# read general variables for common use
params <- yaml::read_yaml(paste0(here::here(), "/Plots/_variables.yml"))

# source utility functions
run_scen(i_scen, "own")

```

## proportion of cooperative housing

### proportions (based on apartments and people)

```{r}
#| label: fig-1200
#| fig-cap: proportion of cooperative housing
#| fig-width: 12
#| fig-height: 14

sszplot(own_prop,
  aes_x = "year", aes_y = "prop", aes_col = "category",
  labs_y = "proportion of cooperative housing (in %)",
  wrap = "district", ncol = 4,
  scale_y = c(0, NA),
  name = plot_name("1200_proportion-cooperative-housing"),
  width = 12, height = 14
)
```

## prediction
category: people
WHY? prediction is based on different sources
projects: apartments
reserves: m2
however, the combined prediction is for persons
therefore, the proportion based on people

```{r}
#| label: fig-1201
#| fig-cap: prediction of proportion of cooperative housing
#| fig-width: 12
#| fig-height: 14

sszplot(own_past_pred,
  aes_x = "year", aes_y = "own_all",
  labs_y = "proportion of cooperative housing (in %)",
  wrap = "district", ncol = 4,
  i_x = c(own_base_begin, own_base_end),
  scale_y = c(0, NA),
  name = plot_name("1201_proportion-cooperative-housing_prediction"),
  width = 12, height = 14
)
```
