project:
  output-dir: "../3_Results/book"
  execute-dir: project
  type: book

book:
  title: "Plots for population scenarios"
  author: "Klemens Rosin, Daniel Baumgartner"
  date: today
  page-navigation: true
  search: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - 01_birth.qmd
    - 02_death.qmd
    - 03_immigration.qmd
    - 04_emigration.qmd
    - 05_reloc_immigration.qmd
    - 06_reloc_emigration.qmd
    - 07_naturalization.qmd
    - 08_careb.qmd
    - 09_living_space.qmd
    - 10_allocation.qmd
    - 11_projects.qmd
    - 13_housing.qmd
    - 14_dem_house.qmd
    - 15_model_output.qmd

toc: true
toc-depth: 4
number-sections: true
format:
  html:
    # theme: cosmo
    code-fold: true
    df-print: kable
    embed-resources: false
    css: "sszTheme.css"
    fig-format: svg
    page-layout: full
    fig-width: 15
    fig-height: 8
    column: body
    anchor-sections: true
    smooth-scroll: true
    max-width: "2400"
editor: visual
execute:
  echo: false
  warning: false
  cache: true

knitr:
  opts_chunk: 
    R.options:
      scipen: 999